# Generated by Django 2.0.2 on 2018-05-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(max_length=20)),
                ('assistant', models.CharField(max_length=6)),
                ('feedback', models.TextField()),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
