# Generated by Django 2.0.2 on 2018-06-07 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='consent_exercise',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='min_points',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='points',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sub_id',
            field=models.IntegerField(unique=True),
        ),
    ]
