# Generated by Django 2.0.7 on 2018-08-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='html_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
