# Generated by Django 2.0.7 on 2018-08-17 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_course_html_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assistants',
            field=models.ManyToManyField(blank=True, related_name='my_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='responsibilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
