# Generated by Django 2.0.2 on 2018-05-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_grader_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sub_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
