# Generated by Django 2.0.2 on 2018-06-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20180607_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['done']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='course_id',
            field=models.PositiveIntegerField(default=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='min_points',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
