# Generated by Django 2.0.2 on 2018-07-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20180614_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='consent_exercise',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
