# Generated by Django 2.0.2 on 2018-07-23 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20180720_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='consent_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.Exercise'),
        ),
    ]
