# Generated by Django 2.0.7 on 2018-08-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20180830_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='feedback_base',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
