# Generated by Django 2.0.7 on 2018-09-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_auto_20180831_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='trace',
            new_name='in_grading',
        ),
    ]
