# Generated by Django 2.0.2 on 2018-07-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_auto_20180723_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='consent_exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.Exercise'),
        ),
    ]
