# Generated by Django 2.0.2 on 2018-07-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_auto_20180724_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='trace',
            field=models.BooleanField(default=False),
        ),
    ]
