# Generated by Django 2.0.7 on 2018-09-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_auto_20180904_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='sub_url',
        ),
    ]
