# Generated by Django 2.0.7 on 2018-09-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_auto_20180913_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='work_div',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Automaattinen tasajako'), (1, 'Henkilökunta valitsee työt manuaalisesti')], default=0, verbose_name='Työnjako:'),
        ),
    ]
