# Generated by Django 2.0.2 on 2018-07-25 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='course_id',
        ),
        migrations.AddField(
            model_name='exercise',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='submissions.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
