# Generated by Django 2.0.7 on 2018-09-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_auto_20180925_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='auto_grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
    ]
