# Generated by Django 2.0.7 on 2018-09-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_auto_20180925_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
