# Generated by Django 2.0.7 on 2018-08-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_auto_20180803_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='feedbacks',
            field=models.ManyToManyField(related_name='students', to='submissions.Feedback'),
        ),
    ]
