# Generated by Django 2.0.7 on 2018-08-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_auto_20180803_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='feedbacks',
        ),
        migrations.AddField(
            model_name='feedback',
            name='students',
            field=models.ManyToManyField(related_name='my_feedbacks', to='submissions.Student'),
        ),
    ]
