# Generated by Django 2.0.7 on 2018-09-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_auto_20180925_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, null=True),
        ),
    ]
