# Generated by Django 2.0.7 on 2018-08-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_auto_20180803_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='module_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
