# Generated by Django 2.0.7 on 2018-08-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_exercise_module_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='max_points',
        ),
    ]
