# Generated by Django 2.0.7 on 2018-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_auto_20180926_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='staff_grade',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
