# Generated by Django 2.0.7 on 2018-09-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0016_auto_20180926_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
