# Generated by Django 2.0.7 on 2018-08-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0017_feedback_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='feedback_base',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
