# Generated by Django 2.0.7 on 2018-10-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0017_auto_20180926_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
