# Generated by Django 2.0.7 on 2018-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0018_exercise_feedback_base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['status']},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='done',
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('BASE', 'Pohja'), ('DRAFT', 'Luonnos'), ('DONE', 'Valmis')], default=0),
        ),
    ]
