# Generated by Django 2.0.7 on 2018-10-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0018_auto_20181001_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='feedback_base',
            field=models.FileField(blank=True, null=True, upload_to='feedback_bases/'),
        ),
    ]
