# Generated by Django 2.0.7 on 2018-10-09 11:32

from django.db import migrations, models
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0019_auto_20181006_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='feedback_base',
            field=models.FileField(blank=True, null=True, upload_to=submissions.models.feedback_base_path),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='staff_grade',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
