# Generated by Django 2.0.7 on 2018-08-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0019_auto_20180815_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('BASE', 'Pohja'), ('DRAFT', 'Luonnos'), ('DONE', 'Valmis')], default=None, null=True),
        ),
    ]
