# Generated by Django 2.0.7 on 2018-08-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_auto_20180815_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('BASE', 'Pohja'), ('DRAFT', 'Luonnos'), ('DONE', 'Valmis')]),
        ),
    ]
