# Generated by Django 2.0.7 on 2018-10-10 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_auto_20181009_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='graders',
            field=models.ManyToManyField(blank=True, related_name='my_gradings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='num_of_graders',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='penalty',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='staff_grade',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
