# Generated by Django 2.0.7 on 2018-10-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0021_auto_20181010_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='staff_grade',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='num_of_graders',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='penalty',
            field=models.BooleanField(default=True),
        ),
    ]
