# Generated by Django 2.0.7 on 2018-08-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0021_auto_20180815_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(verbose_name='palaute'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Valitse tallennustapa!'), ('DRAFT', 'Luonnos'), ('READY', 'Valmis')], null=True),
        ),
    ]
