# Generated by Django 2.0.7 on 2018-08-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0022_auto_20180816_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='points',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='pisteet'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Valitse tila: luonnos / valmis'), ('DRAFT', 'Luonnos'), ('READY', 'Valmis')], null=True, verbose_name=''),
        ),
    ]
