# Generated by Django 2.0.7 on 2018-10-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0022_auto_20181010_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='num_of_graders',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
