# Generated by Django 2.0.7 on 2018-08-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0023_auto_20180816_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Luonnos'), (1, 'Valmis')], null=True, verbose_name=''),
        ),
    ]
