# Generated by Django 2.0.7 on 2018-10-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0024_auto_20181011_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='max_points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
