# Generated by Django 2.0.7 on 2018-10-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0025_exercise_max_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='penalty',
            new_name='add_penalty',
        ),
    ]
