# Generated by Django 2.0.7 on 2018-11-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0026_auto_20181025_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='consent_exercise',
        ),
        migrations.AddField(
            model_name='exercise',
            name='grading_ready',
            field=models.BooleanField(default=False),
        ),
    ]
