# Generated by Django 2.0.7 on 2018-11-16 12:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0027_auto_20181112_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='latest_release',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
