# Generated by Django 2.0.7 on 2018-11-20 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0031_auto_20181119_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['status', 'released']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='sub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
