# Generated by Django 2.0.7 on 2018-11-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0033_auto_20181120_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['grading_ready', 'name']},
        ),
    ]
