# Generated by Django 2.0.7 on 2018-11-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0035_auto_20181121_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='sub_time',
        ),
        migrations.AddField(
            model_name='feedback',
            name='grading_time',
            field=models.DateTimeField(null=True),
        ),
    ]
