# Generated by Django 2.0.7 on 2019-01-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0036_auto_20181121_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='api_root',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='aplus_user_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
