# Generated by Django 2.0.7 on 2019-01-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0037_auto_20190123_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='add_auto_grade',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='api_root',
            field=models.URLField(),
        ),
    ]
