# Generated by Django 2.0.7 on 2019-02-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0038_auto_20190127_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='api_root',
            field=models.URLField(null=True),
        ),
    ]
