# Generated by Django 2.0.7 on 2019-03-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0040_auto_20190221_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=None, max_length=200, null=True, unique=True),
        ),
    ]
