# Generated by Django 2.0.7 on 2019-03-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0041_auto_20190308_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
