# Generated by Django 2.0.7 on 2019-06-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0043_auto_20190620_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='not_found_error',
            field=models.BooleanField(default=False),
        ),
    ]
