# Generated by Django 2.0.7 on 2019-07-01 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0045_course_data_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='api_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='assistants',
            field=models.ManyToManyField(blank=True, related_name='courses_assistant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
