# Generated by Django 2.0.7 on 2019-09-04 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0046_auto_20190701_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('lms_instance_id', models.CharField(max_length=255)),
                ('assistants', models.ManyToManyField(blank=True, related_name='courses_assistant', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, related_name='courses_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='assistants',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='module_id',
        ),
        migrations.AddField(
            model_name='course',
            name='exercise_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='api_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='module',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lms_instance_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='api_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='data_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='aplus_user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('aplus_user_id', 'lms_instance_id')},
        ),
        migrations.AddField(
            model_name='course',
            name='base_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.BaseCourse'),
        ),
        migrations.AlterUniqueTogether(
            name='basecourse',
            unique_together={('label', 'lms_instance_id')},
        ),
    ]
