# Generated by Django 2.0.7 on 2019-09-04 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0047_auto_20190905_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='base_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.BaseCourse'),
        ),
        migrations.AlterField(
            model_name='course',
            name='exercise_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='api_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='module',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='lms_instance_id',
            field=models.CharField(max_length=255),
        ),
    ]
