# Generated by Django 2.2.5 on 2019-09-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0050_auto_20190905_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='total_max_points',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
