# Generated by Django 2.0.7 on 2019-09-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0051_exercise_total_max_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='total_max_points',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
