# Generated by Django 2.0.7 on 2020-01-28 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0052_auto_20190909_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='graders_en',
            field=models.ManyToManyField(blank=True, related_name='my_gradings_en', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='grader_lang_en',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Template'), (1, 'Draft'), (2, 'Ready')], default=0),
        ),
    ]
