# Generated by Django 2.0.7 on 2020-02-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0054_auto_20200131_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='not_found_error',
        ),
        migrations.AddField(
            model_name='exercise',
            name='error_state',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
