# Generated by Django 2.0.7 on 2020-09-19 21:25

from django.db import migrations, models
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0055_auto_20200221_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name', 'course_id']},
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='feedback_base',
            new_name='feedback_base_fi',
        ),
        migrations.AddField(
            model_name='exercise',
            name='feedback_base_en',
            field=models.FileField(blank=True, null=True, upload_to=submissions.models.feedback_base_path),
        ),
    ]
