# Generated by Django 2.0.7 on 2020-12-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0056_auto_20200920_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='total_max_points',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
