# Generated by Django 2.2.28 on 2022-05-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0058_auto_20220513_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['stop_polling', 'chapter_num', 'name']},
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='grading_ready',
            new_name='stop_polling',
        ),
    ]
