# Generated by Django 2.2.28 on 2024-12-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0061_auto_20241215_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sub_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
