# Generated by Django 2.2.28 on 2024-12-16 18:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0062_auto_20241215_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='latest_release',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
    ]
