# Generated by Django 2.2.28 on 2025-01-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0063_auto_20241216_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='ending_time',
            field=models.DateTimeField(null=True),
        ),
    ]
